# site settings

title: Avigdor
description: Beginner Python-Developer
taglong: Beginner Python-Developer
tagshort: Jekyll theme
url: https://avigdortietz.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/AvigdorTietz/avigdortietz.github.io

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photka.jpg

# social media links

social:
  facebook: username
  github: AvigdorTietz
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
